name: Build and deploy application
on:
  pull_request:
    types:
      - opened
    branches:
      - main
      - develop
      - "feature/**"
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      - "feature/**"
    paths-ignore:
      - ".github/workflows/*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print event details
        run: echo "${{ toJSON(github.event) }}"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run test cases
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying project"
